### ISSUE TITLE
How to restore to the original material in the material extension?

### ISSUE THREAD

**Issue by ycjcl868** [Developer-Autodesk/library-javascript-viewer-extensions#10]
![image](https://cloud.githubusercontent.com/assets/13595509/17547369/5f185ae6-5f19-11e6-943f-93913db88dfa.png)

**Comment by autodesk-adn** [comment]
The extension was not designed to do this. This sample was to show how to change material using a user defined new material. If you wish to restore the original material, you need to save the original material definition before assigning the new material, and implement a reset functionality.
