### ISSUE TITLE
Annotation.js:680 Uncaught ReferenceError: async is not defined

### ISSUE THREAD

**Issue by ycjcl868** [Developer-Autodesk/library-javascript-viewer-extensions#11]
![9ed3a1fc-f75a-4dcd-8286-92cbe6424013](https://cloud.githubusercontent.com/assets/13595509/17895027/45b5cb28-697e-11e6-8858-3705474ee295.png)

![image](https://cloud.githubusercontent.com/assets/13595509/17894865/9602f340-697d-11e6-92eb-42642402dd5b.png)

**Comment by leefsmp** [comment]
you need to add a reference to the [async](https://github.com/caolan/async) library in your html for this extension to work
