### ISSUE TITLE
Use require at JavaScript client side

### ISSUE THREAD

**Issue by khoaho** [Developer-Autodesk/library-javascript-viewer-extensions#13]
Hi,

I am playing with the Chart extension and seeing it fails to run `require(dependencies, function() { }` at the link:
https://github.com/Developer-Autodesk/library-javascript-viewer-extensions/blob/master/src/Autodesk.ADN.Viewing.Extension.Chart/Autodesk.ADN.Viewing.Extension.Chart.js#L41

Why we need `require` here. I try to reference RequireJS (http://requirejs.org/) to my code but it still does not work. The original blog at http://adndevblog.typepad.com/cloud_and_mobile/2015/07/integrating-a-charting-library-with-view-data-api.html did not use `require`.

I would like to run this extension at client side, without Node.js

Thank you,
Khoa

**Comment by khoaho** [comment]
I end up to use a custom JavaScript method `require` to load dependencies (*.js & *.css) on request:

``` javascript
window.require = function () {
    var index = 0;
    return function (files, callback) {
        if (files instanceof Array) {
            index += 1;
            // Recursive call for each file
            require(files[index - 1], callBackCounter);
            function callBackCounter() {
                if (index === files.length) {
                    index = 0;
                    callback();
                } else {
                    require(files, callback);
                }
            };
        } else {
            callback = callback || function () { };
            var filenode;
            var jsfile_extension = /(.js)$/i;
            var cssfile_extension = /(.css)$/i;
            if (jsfile_extension.test(files)) {
                filenode = document.createElement('script');
                filenode.src = files;
                // IE
                filenode.onreadystatechange = function () {
                    if (filenode.readyState === 'loaded' || filenode.readyState === 'complete') {
                        filenode.onreadystatechange = null;
                        callback();
                    }
                };
                // Others
                filenode.onload = function () {
                    callback();
                };
                document.head.appendChild(filenode);
            } else if (cssfile_extension.test(files)) {
                filenode = document.createElement('link');
                filenode.rel = 'stylesheet';
                filenode.type = 'text/css';
                filenode.href = files;
                document.head.appendChild(filenode);
                callback();
            } else {
                console.log("Unknown file type to load.")
            }
        }
    };
}();
```

**Comment by leefsmp** [comment]
In my demo website [http://gallery.autodesk.io](http://gallery.autodesk.io) each extension is loaded dynamically on demand, so I use requireJS to load dependencies of an extension if needed. If you run a custom example, you do not need to use that approach, you can simply include the required .js/.css from your html.

**Comment by khoaho** [comment]
Hi Philippe,

I don't use node.js to build my web app, so I am using use the above `require` JavaScript method to load additional .js/.css files on demand, without loading lots of unused .js files at the beginning. Most of the extensions work great but some do not. I am still working on it.

Thanks,
Khoa

**Comment by leefsmp** [comment]
This has nothing to do with using node.js or not, it only concerns loading loading dependencies on the browser, so unrelated to your backend technology. I would recommend you to use [SystemJS](https://github.com/systemjs/systemjs) in order to load additional scripts, it is a nice and powerful library. If you have specific issues with some extensions please be more specific why it doesn't work.

**Comment by khoaho** [comment]
Thank you for your suggestion with SystemJS. I am working to fix errors of missing dependencies of multiple viewing extensions.
