### ISSUE TITLE
Extensions With Dependencies Won't Deploy

### ISSUE THREAD

**Issue by sramseier** [Developer-Autodesk/library-javascript-viewer-extensions#2]
Hello, I have basically followed the steps at https://github.com/Developer-Autodesk/tutorial-getting.started-view.and.data/blob/master/chapter-3.md#Step2 to add these extensions to the viewer. This seems to work for most except those with dependencies (most interested in the Chart extension), I am sure to load the dependencies first in the index.html file and have changed paths for local deployment but have had no success deploying locally or via Heroku.
Any help is greatly appreciated!

**Comment by leefsmp** [comment]
Hi, do you see any error message in the browser console? Did you try to debug the js code and see if your code is entering the extension load method? 

Are you using the code from the following post:
http://adndevblog.typepad.com/cloud_and_mobile/2015/07/integrating-a-charting-library-with-view-data-api.html

The only thing you would need is to reference the chart.js dependency, the extension file and do a viewer.loadExtension('Chart extension Id')

Hope that helps,
Philippe.

**Comment by sramseier** [comment]
Thanks for the quick response! The code from your link works, I had previously been using the script from:
https://github.com/Developer-Autodesk/library-javascript-viewer-extensions/blob/master/Autodesk.ADN.Viewing.Extension.Chart/Autodesk.ADN.Viewing.Extension.Chart.js

It seems the only difference is the script on github has a dependencies variable and require function called out on lines 37-41
