### ISSUE TITLE
viewer.clearSelection() not clearing anything

### ISSUE THREAD

**Issue by vladotesanovic** [Developer-Autodesk/library-javascript-viewer-extensions#3]
Hey there,

I'm trying to build few plugins for viewer, one of the plugin are Hide & Show elements...

I can retrieve what user select with: 

``` javascript
_hiddenElements = viewer.getSelection();
 viewer.hide(_hiddenElements);
```

That works nicely. 

When I try to clear selection and show hidden elements, i tried with:

``` javascript
for(var index in _hiddenElements) {
  viewer.show(_hiddenElements[index]);
}

_hiddenElements = [];
viewer.clearSelection(); // This function don't do anything
```

When i run viwer.getSeleciton() After viewer.clearSelection() i get array of all selected elements...

**Comment by leefsmp** [comment]
to unselect all components, you can pass an empty array to select method: viewer.select([ ])

Also using SELECTION_CHANGED_EVENT might be more appropriate to retrieve user selection:
http://adndevblog.typepad.com/cloud_and_mobile/2015/10/event-watcher-extension-for-view-data.html

Hope that helps,
Philippe.

**Comment by vladotesanovic** [comment]
Ok, 

I was able to solve it with event SELECTION_CHANGED_EVENT ( i forgot about this event ). I want to hide one and show only last hidden element...

It works and code is here: https://github.com/vladotesanovic/library-javascript-viewer-extensions/blob/master/Viewing.Extension.HideElement/Viewing.Extension.HideElement.js

Again, viewer.select([ ]) does not clear selection,  function viwer.getSeleciton() retrieve all previously selected elements. 

I also use this function to reset elements in viewer: viewer.isolate(); works visually at least.

**Comment by leefsmp** [comment]
viewer.select([ ]) clears the graphics (selection on screen) but may not clear the API as you mentioned.
