### ISSUE TITLE
document list of extensions

### ISSUE THREAD

**Issue by jeremytammik** [Developer-Autodesk/library-javascript-viewer-extensions#4]
please add documentation to the repo readme, listing what each extension does and which lmv functions it exercises. otherwise, how am i supposed to find what i need? thank you!

**Comment by leefsmp** [comment]
Pretty obvious to take a guess from the extension name, but I will add a quick description. Listing exactly which LMV functions each extension is using is a bit too much to ask ...

**Comment by cyrillef** [comment]
listing each method might be too much - I agree
but a readme in each extension make sense. For example: Autodesk.ADN.Viewing.Extension.PropertyTranslator
what is that? you translate to French, German, etc... or is it something else?
A minimal description and logic would be welcome

**Comment by leefsmp** [comment]
done, added description for each entry.
