### ISSUE TITLE
Markup3D Extension not working

### ISSUE THREAD

**Issue by PriyankBhatt** [Developer-Autodesk/library-javascript-viewer-extensions#5]
Hi,
I have compiled the the code using the instruction given and now i am loading the Markup3D extension on sketchup file but the extension is not clickable also i am not getting any error on console as well. I am attaching a screenshot.

<img width="1440" alt="screen shot 2016-07-06 at 1 47 53 pm" src="https://cloud.githubusercontent.com/assets/8079399/16612144/0e6624c2-4383-11e6-859b-37c230f71843.png">

And here is the code:
`<body>
        <div id="MyViewerDiv"></div>

```
    <!-- The Viewer JS -->
    <script   src="https://code.jquery.com/jquery-3.0.0.min.js"></script>

    <script src="https://developer.api.autodesk.com/viewingservice/v1/viewers/three.min.js"></script>
    <script src="https://autodeskviewer.com/viewers/2.5/viewer3D.min.js"></script>
    <script src="https://developer.api.autodesk.com/viewingservice/v1/viewers/Autodesk360App.js"></script>
    <script src="./App/extensions/Viewing.Extension.Markup3D/Viewing.Extension.Markup3D.js"></script>

    <!-- <script src="testextension.js"></script> -->

    <!-- Developer JS -->
    <script>
        var viewerApp;
        var options = {
            env: 'AutodeskProduction',
            accessToken: 'XXXXXXXX'
        };
        var config3d = {
          extensions: ['Viewing.Extension.Markup3D']
        };
        var documentId = 'urn:XXXXXXXXXXXX';
        Autodesk.Viewing.Initializer(options, function onInitialized(){
            viewerApp = new Autodesk.A360ViewingApplication('MyViewerDiv');
            // viewerApp.loadExtension("Autodesk.Viewing.Markups", loadOptions);
            viewerApp.registerViewer(viewerApp.k3D, Autodesk.Viewing.Private.GuiViewer3D, config3d);
            viewerApp.loadDocumentWithItemAndObject(documentId);
        });
    </script>
`
```

**Comment by leefsmp** [comment]
The extension expects bootstrap css to be loaded in order to get the glyphicon in the button, but I don't think this is the issue. I see 8 errors in the console, what are those? Not sure what you mean by "not clickable"... Is there any error thrown when you click the button?

**Comment by PriyankBhatt** [comment]
The Button is not clickable and their isn't any error thrown when i clicked the button. Also while transpiling the code initially i had `regeneratorRuntime is not defined` error so i added `['babel-polyfill','./src/Viewing.Extension.Markup3D/Viewing.Extension.Markup3D.js'],` in webpack in order to remove the error. And the 8 errors that were shown were from autodesk 

> Image from origin 'https://autodeskviewer.com' has been blocked from loading by Cross-Origin Resource Sharing policy: A wildcard '*' cannot be used in the 'Access-Control-Allow-Origin' header when the credentials flag is true. Origin 'null' is therefore not allowed access.

**Comment by leefsmp** [comment]
try adding the babel-polyfill to your application, this needs to be loaded prior any transpiled file is loaded

**Comment by PriyankBhatt** [comment]
I am newbie in this so these are the steps i followed
1. Made an html file with viewer code.
2. Used Model derivative api to translate the skp file
3. I cloned your repo and did npm install
4. Added the Markup3D.js in the main html file
After doing this error started coming from ViewerToolkit regarding `regeneratorRuntime is not defined` so i added babel-polyfill in webpack.
Now i get in console that Markup3D is loaded but clicking it doesnt seems throw any error or doesnt trigger an activity.

**Comment by leefsmp** [comment]
First try putting console.log in the button handler to see if the code is invoked:

`
      //Viewing.Extension.Markup3D.js
      /////////////////////////////////////////////////////////////////
      // Load callback
      //
      /////////////////////////////////////////////////////////////////
      load () {

```
    this._control = ViewerToolkit.createButton(
      'toolbar-markup3D',
      'glyphicon glyphicon-check',
      'Markup 3D', () => {

         console.log('button clicked ...')

       //... 
```

`

You are adding the file generated by webpack to the html and not the 'Viewing.Extension.Markup3D.js' from the source folder correct? 

Once you click the button added by the extension, you need to select a component on the viewer in order to create the first markup

Hope that helps

**Comment by PriyankBhatt** [comment]
Yup got it Thanks. I thought Markup3D would be similar to Markup2D so i was waiting for the panel to open.So in Markup3D i just can annotate a particular region and not put marker on it right ?

**Comment by leefsmp** [comment]
yep, so it was working from the start :) 

Markup2D is a custom panel I created that illustrates how to use the svg Markup API, see there for more details:
[http://adndevblog.typepad.com/cloud_and_mobile/2016/02/playing-with-the-new-view-data-markup-api.html](http://adndevblog.typepad.com/cloud_and_mobile/2016/02/playing-with-the-new-view-data-markup-api.html)

Markup3D is a feature I created from scratch, provided as a demo sample:
[http://adndevblog.typepad.com/cloud_and_mobile/2016/04/markup3d-sample-for-view-data-api.html](http://adndevblog.typepad.com/cloud_and_mobile/2016/04/markup3d-sample-for-view-data-api.html)
