### ISSUE TITLE
 Unexpected token '>'  in RadialMenu Extension 

### ISSUE THREAD

**Issue by ycjcl868** [Developer-Autodesk/library-javascript-viewer-extensions#6]
![c6231c6b-9869-48d3-b10b-cd432a22e73a](https://cloud.githubusercontent.com/assets/13595509/17454159/19ec7130-5bbf-11e6-9f9d-d8e85b4aee46.png)

**Comment by leefsmp** [comment]
Extension is written in ES6, needs transpiling with a tool like babel or traceur
