### ISSUE TITLE
ReferenceError: Raphael is not defined in Annotation Extension

### ISSUE THREAD

**Issue by ycjcl868** [Developer-Autodesk/library-javascript-viewer-extensions#8]
![image](https://cloud.githubusercontent.com/assets/13595509/17454607/0fcd0e8e-5bcf-11e6-8c26-2fa93a0a3a1c.png)

**Comment by leefsmp** [comment]
You need to include the raphael.min.js script prior to load that extension, it is included in the source at: [`https://github.com/Developer-Autodesk/library-javascript-viewer-extensions/tree/master/src/Autodesk.ADN.Viewing.Extension.Annotation`](https://github.com/Developer-Autodesk/library-javascript-viewer-extensions/tree/master/src/Autodesk.ADN.Viewing.Extension.Annotation)
